# application-dev.yml - Development profile  
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:realestatecrm_dev
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect